export const studyCases = [
  {
    name: 'godaddy',
    focusPoints: ['e-Commerce', 'Enterprise'],
    title: 'Built a product for SMB’s to manage their business.',
    description: 'Solving problems for Small, medium businesses to generate leads, manage products, customer engagement and WoW product delivery. Explore the opportunity to build a product that helps SMBs to grow their business and keep the customers engaged.',
    services: ['User Research', 'User Testing', 'UI Design', 'Wireframe', 'User Interviews', 'MVP', 'Development'],
    backgroundColor: '#96DCDC',
    href: 'go-daddy',
  },
  {
    name: 'arrow',
    focusPoints: ['Heavy equipment machinery', 'Startup'],
    title: 'Streamline deal closing process easy and fast.',
    description: 'Arrow is leading CRM software focusing on heavy equipment industry and made sales process easy. It is a modern platform to manage Inventory, search inventory, Internal feed where team member can post images, video, share product, news, marketing campaigns, custom invoice templates, esign docs, eCommerce experience, finance, closing big deals, reserve online facility, internal chat (team members), external chat (customers) and much more.',
    services: ['Design', 'Development', 'Store front', 'Branding', 'Advertising', 'Hybrid mobile app', 'MVP', 'B2B', 'B2C'],
    backgroundColor: '#F0DDE5',
    href: 'hey-arrow',
  },
  {
    name: 'accord',
    focusPoints: ['Sales & Marketing', 'Software', 'Startup', 'Y-Combinator'],
    title: 'Consistent Sales & CS Execution',
    description: 'Standardize winning business cases, account plans, multi-threading, and mutual action plans. Up-level execution to drive win rates, time-to-live and customer outcomes.',
    services: ['Branding', 'Concept Development', 'Fund Raising', 'CRM', 'Sales', 'Website Design', 'Development'],
    backgroundColor: '#F0EEF7',
    href: 'in-accord',
  },
  {
    name: 'faceoff',
    focusPoints: ['Gaming'],
    title: 'FaceOff The Emotion Capture & Guessing Game',
    description: 'FaceOff is an mobile application that combines the excitement of taking pictures with the mystery of guessing about emotions. The idea is straightforward yet really engaging. When the first user captures the moment, the second user must use their instincts to figure out what emotion is being conveyed in the picture.',
    services: ['Branding', 'Application Design', 'Wireframe', 'UI Design', 'Development'],
    backgroundColor: '#DDE2F0',
    href: 'faceoff',
  },
]